P2p/digital ipfs
PoCInnovation/Workshops pull request #17
Opened 2021-08-06 12:35 UTC by NaadiQmmr

2021-08-06 13:50 UTC, TomChv requested changes
Nice jobs! I've added some comments and suggestion.
I didn't review the code but you should add a zip of the source code to download it easily.

Global comments : 
- Sometimes you use `your` and sometimes `our`, stay logic
- You could use more smileys :100: 
- Remove `pycache` files

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +```
Maybe add some instruction instead of just the command

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +The number `a998a543950c` is the id of your container, it's ok if yours is different.
```suggestion
> :bulb: The number `a998a543950c` is the id of your container, it's ok if yours is different.
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +If you want to shut down the server, use `Ctrl` + `C` and then run `docker-compose down`.
```suggestion
If you want to shut down the server, use `Ctrl` + `C` and then run `docker-compose down -v`.
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +Go to [this](https://freemusicarchive.org/music/Scott_Holmes/rock-background-music/country-road-drive) website and download the song.
This doesn't mean anything, put your link on the real content. 
Example
Go to the [music website](a link) ...

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +You can find the code of the form in `./musichare/forms.py`, and the associate model object in `./musicshare/models.py`.
```suggestion
You can find the code of the form in [./musichare/forms.py](./musichare/forms.py), and the associate model object in [./musicshare/models.py](./musicshare/models.py).
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +the first part of the message is obviously the datetime. The second one is the method, `GET`, because we want to just
```suggestion
The first part of the message is obviously the datetime. The second one is the method, `GET`, because we want to just
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +that the server is ok to give us that page from the `/` route, and it has been delivered correctly.
Maybe a [flowchart](https://en.wikipedia.org/wiki/Flowchart) you'll be more accurate

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +`POST` is another **method** than `GET`. When you fill the form earlier, it was **you** that was giving the server
```suggestion
`POST` is another **http method** than `GET`. When you fill the form earlier, it was **you** that was giving the server
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +>What does `POST` means ?
```suggestion
> :bulb: What does `POST` means ?
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +You can find all HTTP methods [here](https://www.restapitutorial.com/lessons/httpmethods.html).
```suggestion
> :bulb: [Learn more about HTTP methods](https://www.restapitutorial.com/lessons/httpmethods.html).
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +Now, look at your `/media/static` folder : you have the mp3 file you just downloaded in here !
```suggestion
Now, look at your [./media/static](./media/static) folder : you have the mp3 file you just downloaded in here !
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +get, joined by a /. That format does not ring a bell to you ? It is like a path !
```suggestion
> :bulb: This is how HTTP works. When retrieving data, HTTP focuses on **location**. Have you noticed the url ?
First, it is `0.0.0.0` which is your local IP; then: `8000` to signify the port. Finally, the routes or file you want to
get, joined by a `/`. That format does not ring a bell to you ? It is like a path!
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +Instead of referring to data (photos, articles, videos) by **location**, or which server they are stored on, IPFS refers to everything by that data’s hash, meaning the **content itself.**
Put a link on what is a hash and distributed system

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +If this is not enough clear for you, I strongly advise you to refer to [this](https://www.youtube.com/watch?v=5Uj6uR3fp-U) video.
Same, put on link on the content, not simply |this] because it has no sense

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +3. Open `musicshare/templates/musicshare/index.html` to line `179` and make sure the hash of the song appears.
Replace path by a link
Example
`./toto` -> [./toto](./toto)

This way, they can directly click on the link to go to the file

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +You should see your song play, even if your server has been shut down !
```suggestion
Test another time to upload your music, copy past the hash of the newly added song and go to `https://ipfs.infura.io:5001/api/v0/cat?arg={your_hash_here}`.
You should see your song play, even if your server has been shut down !
```

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +Since you did the previous step, this one would seem easy : in your `musicshare/view.py` on the `download` view,
convert path to link

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +[Here](https://docs.ipfs.io/how-to/command-line-quick-start) is how you can deploy and configure your own IPFS node.
Where are authors and bonuses and organization? Check that [workshop](https://github.com/PoCInnovation/Workshops/tree/master/software/17.gRPC#rocket-to-go-further) for example

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/README.md
> +[Here](https://docs.ipfs.io/how-to/command-line-quick-start) is how you can deploy and configure your own IPFS node.
Here mean nothing

You should also add links to open source project around ipfs like orbit db :rocket:

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/SETUP.md
> +### [Installation on Fedora](https://docs.docker.com/engine/install/fedora/)
Use docker workshop setup for that part
As well, where can I get the code of your platform ? It should be in the setup

2021-08-06 13:50 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/SETUP.md
> +And that is it !
```suggestion
And that is it !

[Go back to the exercise](./README.md)
```

2021-08-06 14:46 UTC, PtitLuca commented on p2p/3.IPFS_or_HTTP/Dockerfile
> +CMD ["sh", "launch.sh"]
Comments ^^

2021-08-06 14:53 UTC, PtitLuca commented on p2p/3.IPFS_or_HTTP/musicshare/views.py
> +                Don't forget to create a new Song object and store the hash !
You could give a link to the Infura Documentation.
I think [this one](https://infura.io/docs/ipfs) is the one you're looking for here.

2021-08-06 14:54 UTC, PtitLuca requested changes
- You should remove the pycache folder

2021-08-07 14:39 UTC, TomChv requested changes
LGTM, minor comments on `SETUP.md`

2021-08-07 14:39 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/SETUP.md
> +In order to launch our music platform, you have to download a few things and unzip the zip folder
download a few things? And what are those things?

2021-08-07 14:39 UTC, TomChv commented on p2p/3.IPFS_or_HTTP/SETUP.md
> +* `unzip sources.zip ; cd sources`
Where can I get `sources.zip` ?

2021-08-07 15:24 UTC, TomChv approved these changes
LGTM

2021-08-07 16:36 UTC, merged